inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/environments/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/ImplicitExpect:
  EnforcedStyle: should
